name: cicd

#it will only run, when we trigger it manually
on:
  workflow_dispatch:
    inputs:
      environment:
        description: this is the environment value where this workflow run
        default: 'dev'
        required: true
        type: choice
        options:
          - dev
          - prod
          - staging

jobs:
#every job needs seperate runner, its called parallelism
  code:
    runs-on: ubuntu-latest
    steps:
      - name: pull the code
        run: echo "code clone from github  successful"
  build:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: build the code
        run: echo "code build successfully"
  test:
    needs: [code, build]
    runs-on: ubuntu-latest
    steps:
      - name: test the code
        run: echo "code test successful"
          
  deploy:
    needs: [code, build, test]
    runs-on: ubuntu-latest
    steps:
      - name: deploy the code
        run: echo "code deployement successful"
